import { NextRequest, NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminAuth, getAdminDb } from "@/lib/firebase-admin";
import { HttpError, errorResponseDetails, requireServerActor } from "@/lib/server-auth";
import { recordSystemAlert } from "@/lib/security-events-server";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const MAX_ALERT_TEXT = 240;
const SUPER_ADMIN_EMAIL = "wisdomasaare41@gmail.com";

type Summary = {
  sales: number;
  invoices: number;
  payments: number;
  folios: number;
  failures: number;
  total: number;
};

type SyncResult = { synced: number; failed: number };
type AlertResult = { duplicate: boolean; status: "duplicate" | "sent" | "failed" | "skipped" | "queued"; reason?: string };
type TelemetryRecord = SyncTelemetryLike & { id: string };
type SyncTelemetryLike = {
  businessId?: string;
  sales?: number;
  invoices?: number;
  payments?: number;
  folios?: number;
  failures?: number;
  total?: number;
  offlineMode?: boolean;
  lastSeenAt?: unknown;
  lastSyncAt?: unknown;
  lastSyncResult?: SyncResult;
};
type AlertRecord = { id: string; businessId?: string; createdAt: string | null; emailedAt: string | null; [key: string]: unknown };

function responseError(status: number, error: string) {
  return NextResponse.json({ error }, { status, headers: { "cache-control": "no-store" } });
}

function boundedString(value: unknown, max = MAX_ALERT_TEXT) {
  return typeof value === "string" ? value.trim().slice(0, max) : "";
}

function nonNegativeInt(value: unknown) {
  return typeof value === "number" && Number.isInteger(value) && value >= 0 ? value : 0;
}

function normalizeSummary(input: unknown): Summary {
  const value = input && typeof input === "object" ? input as Record<string, unknown> : {};
  const sales = nonNegativeInt(value.sales);
  const invoices = nonNegativeInt(value.invoices);
  const payments = nonNegativeInt(value.payments);
  const folios = nonNegativeInt(value.folios);
  const failures = nonNegativeInt(value.failures);
  const total = sales + invoices + payments + folios;
  return { sales, invoices, payments, folios, failures, total };
}

function normalizeSyncResult(input: unknown): SyncResult | null {
  if (!input || typeof input !== "object") return null;
  const value = input as Record<string, unknown>;
  if (typeof value.synced !== "number" || typeof value.failed !== "number") return null;
  return { synced: nonNegativeInt(value.synced), failed: nonNegativeInt(value.failed) };
}

async function getBusinessRecipient(businessId: string) {
  const firestore = getAdminDb();
  const [profileSnap, registrationSnap] = await Promise.all([
    firestore.collection("businessProfiles").doc(businessId).get(),
    firestore.collection("businesses").doc(businessId).get(),
  ]);
  const profile = profileSnap.data() || {};
  const registration = registrationSnap.data() || {};
  return {
    businessName: boundedString(profile.businessName || registration.businessName, 180) || "BillFlow business account",
    email: boundedString(profile.ownerEmail || profile.email || registration.email, 320),
  };
}

async function sendAdminEmail(params: {
  recipientEmail: string;
  businessName: string;
  subject: string;
  message: string;
  details: string;
}) {
  if (!params.recipientEmail) return { status: "skipped" as const, reason: "No administrator email is configured" };
  const html = `<!doctype html><html><body style="margin:0;background:#f4f7fb;color:#111827;font-family:Arial,Helvetica,sans-serif"><div style="max-width:720px;margin:0 auto;padding:28px 16px"><div style="background:#fff;border:1px solid #dbe5ef;padding:24px"><p style="margin:0 0 16px;color:#1556B8;font-size:18px;font-weight:700">BillFlow · ${params.businessName}</p><h2 style="margin:0 0 12px;font-size:20px">${params.subject}</h2><p style="margin:0 0 16px;line-height:1.6">${params.message}</p><p style="margin:0;line-height:1.6;color:#475569">${params.details}</p><p style="margin:22px 0 0;color:#64748b;font-size:12px">This operational alert was generated by BillFlow.</p></div></div></body></html>`;
  const resendKey = boundedString(process.env.RESEND_API_KEY, 500);
  const from = boundedString(process.env.RESEND_FROM_EMAIL, 320);
  if (resendKey && from) {
    try {
      const response = await fetch(process.env.RESEND_API_URL || "https://api.resend.com/emails", {
        method: "POST",
        headers: { Authorization: `Bearer ${resendKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({ from, to: [params.recipientEmail], subject: params.subject, html }),
        cache: "no-store",
      });
      return response.ok
        ? { status: "sent" as const }
        : { status: "failed" as const, reason: `Email provider returned HTTP ${response.status}` };
    } catch (error) {
      return { status: "failed" as const, reason: error instanceof Error ? error.message : "Email provider request failed" };
    }
  }

  const webhookUrl = boundedString(process.env.SCHOOL_EMAIL_WEBHOOK_URL, 1000);
  if (webhookUrl) {
    try {
      const response = await fetch(webhookUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(boundedString(process.env.SCHOOL_EMAIL_WEBHOOK_SECRET, 500)
            ? { Authorization: `Bearer ${process.env.SCHOOL_EMAIL_WEBHOOK_SECRET}` }
            : {}),
        },
        body: JSON.stringify({
          event: "billflow.offline.alert",
          recipientEmail: params.recipientEmail,
          businessName: params.businessName,
          subject: params.subject,
          message: params.message,
          details: params.details,
          html,
        }),
        cache: "no-store",
      });
      return response.ok
        ? { status: "sent" as const }
        : { status: "failed" as const, reason: `Email webhook returned HTTP ${response.status}` };
    } catch (error) {
      return { status: "failed" as const, reason: error instanceof Error ? error.message : "Email webhook request failed" };
    }
  }

  return { status: "queued" as const, reason: "No administrator email delivery provider is configured" };
}

async function createAlertOnce(params: {
  businessId: string;
  alertKey: string;
  type: string;
  title: string;
  message: string;
  severity: "info" | "warning" | "critical";
  details: string;
}) {
  const firestore = getAdminDb();
  const alertRef = firestore.collection("offlineAlerts").doc(params.alertKey);
  try {
    await alertRef.create({
      businessId: params.businessId,
      type: params.type,
      title: params.title,
      message: params.message,
      severity: params.severity,
      emailStatus: "pending",
      createdAt: FieldValue.serverTimestamp(),
    });
  } catch (error) {
    if ((error as { code?: number })?.code === 6) return { duplicate: true, status: "duplicate" as const };
    throw error;
  }

  const recipient = await getBusinessRecipient(params.businessId);
  const delivery = await sendAdminEmail({
    recipientEmail: recipient.email,
    businessName: recipient.businessName,
    subject: params.title,
    message: params.message,
    details: params.details,
  });
  await alertRef.update({
    emailStatus: delivery.status,
    ...(delivery.reason ? { emailReason: delivery.reason } : {}),
    ...(delivery.status === "sent" ? { emailedAt: FieldValue.serverTimestamp() } : {}),
  });
  await firestore.collection("notifications").add({
    businessId: params.businessId,
    type: params.type,
    title: params.title,
    message: params.message,
    severity: params.severity,
    isRead: false,
    createdAt: FieldValue.serverTimestamp(),
  });
  await recordSystemAlert({
    severity: params.severity,
    eventType: `offline_${params.type}`,
    message: params.message,
    businessId: params.businessId,
    metadata: { emailStatus: delivery.status },
  });
  return { duplicate: false, status: delivery.status } satisfies AlertResult;
}

async function requireBusinessActor(request: NextRequest, businessId: string) {
  const actor = await requireServerActor(request);
  if (!businessId || businessId !== actor.businessId) throw new HttpError(403, "Business context does not match the signed-in account");
  return actor;
}

async function requireSuperAdmin(request: NextRequest) {
  const authorization = request.headers.get("authorization");
  if (!authorization?.startsWith("Bearer ")) throw new HttpError(401, "Authentication required");
  let decoded;
  try {
    decoded = await getAdminAuth().verifyIdToken(authorization.slice(7), true);
  } catch {
    throw new HttpError(401, "Invalid or expired session");
  }
  if ((decoded.email || "").toLowerCase() !== SUPER_ADMIN_EMAIL) throw new HttpError(403, "Super Admin access required");
  return decoded;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const action = boundedString(body?.action, 40);
    const businessId = boundedString(body?.businessId, 160);
    if (action === "request_sync") {
      await requireSuperAdmin(request);
      if (!businessId) throw new HttpError(400, "Business context is required for a manual sync command");
    } else {
      await requireBusinessActor(request, businessId);
    }
    const firestore = getAdminDb();

    if (action === "telemetry") {
      const summary = normalizeSummary(body?.summary);
      const syncResult = normalizeSyncResult(body?.syncResult);
      const now = new Date().toISOString();
      await firestore.collection("syncTelemetry").doc(businessId).set({
        businessId,
        ...summary,
        offlineMode: body?.offlineMode === true,
        lastSeenAt: now,
        ...(syncResult ? { lastSyncAt: now, lastSyncResult: syncResult } : {}),
      }, { merge: true });

      let alert: AlertResult | null = null;
      if (syncResult?.failed && syncResult.failed > 0) {
        const day = now.slice(0, 10);
        alert = await createAlertOnce({
          businessId,
          alertKey: `${businessId}_sync_failure_${day}`,
          type: "sync_failure",
          title: "Offline sync requires attention",
          message: `${syncResult.failed} offline record${syncResult.failed === 1 ? "" : "s"} failed to synchronize for this account.`,
          severity: "warning",
          details: `Last attempt synchronized ${syncResult.synced} record${syncResult.synced === 1 ? "" : "s"} and left ${syncResult.failed} record${syncResult.failed === 1 ? "" : "s"} queued for review.`,
        });
      }
      return NextResponse.json({ ok: true, telemetry: { ...summary, businessId, offlineMode: body?.offlineMode === true, lastSeenAt: now, ...(syncResult ? { lastSyncAt: now, lastSyncResult: syncResult } : {}) }, alert }, { headers: { "cache-control": "no-store" } });
    }

    if (action === "auto_switch") {
      const day = new Date().toISOString().slice(0, 10);
      const alert = await createAlertOnce({
        businessId,
        alertKey: `${businessId}_offline_auto_switch_${day}`,
        type: "offline_auto_switch",
        title: "Offline mode automatically disabled",
        message: "This account was switched back to Online mode after reaching the three-day offline limit.",
        severity: "info",
        details: "Reconnect synchronization can now proceed. Review the Offline Sync Monitor if queued records remain.",
      });
      return NextResponse.json({ ok: true, alert }, { headers: { "cache-control": "no-store" } });
    }

    if (action === "low_stock") {
      const productId = boundedString(body?.productId, 160) || "unknown";
      const productName = boundedString(body?.productName, 180) || "A product";
      const stockQty = nonNegativeInt(body?.stockQty);
      const reorderLevel = nonNegativeInt(body?.reorderLevel);
      const day = new Date().toISOString().slice(0, 10);
      const alert = await createAlertOnce({
        businessId,
        alertKey: `${businessId}_low_stock_${productId}_${day}`,
        type: "low_stock",
        title: "Low-stock alert",
        message: `${productName} is at or below its reorder level.`,
        severity: "warning",
        details: `Current stock: ${stockQty}. Reorder level: ${reorderLevel}.`,
      });
      return NextResponse.json({ ok: true, alert }, { headers: { "cache-control": "no-store" } });
    }

    if (action === "request_sync") {
      const commandRef = await firestore.collection("syncCommands").add({
        businessId,
        requestedBy: "admin",
        status: "requested",
        createdAt: FieldValue.serverTimestamp(),
      });
      return NextResponse.json({ ok: true, commandId: commandRef.id }, { headers: { "cache-control": "no-store" } });
    }

    throw new HttpError(400, "Unsupported offline-sync action");
  } catch (error) {
    const details = errorResponseDetails(error);
    return responseError(details.status, details.message);
  }
}

export async function GET(request: NextRequest) {
  try {
    const actor = await requireSuperAdmin(request);
    const firestore = getAdminDb();
    const profilesSnapshot = await firestore.collection("businessProfiles").orderBy("businessName").get();
    const registrationsSnapshot = await firestore.collection("businesses").get();
    const telemetrySnapshot = await firestore.collection("syncTelemetry").get();
    const alertsSnapshot = await firestore.collection("offlineAlerts").orderBy("createdAt", "desc").limit(100).get();
    const registrations = new Map(registrationsSnapshot.docs.map((document) => [document.id, document.data()]));
    const telemetry: TelemetryRecord[] = telemetrySnapshot.docs.map((document) => ({ id: document.id, ...(document.data() as Record<string, unknown>) } as TelemetryRecord));
    const alerts: AlertRecord[] = alertsSnapshot.docs.map((document) => {
      const data = document.data() as Record<string, unknown>;
      const createdAt = data.createdAt && typeof data.createdAt === "object" && "toDate" in data.createdAt && typeof (data.createdAt as { toDate?: unknown }).toDate === "function"
        ? (data.createdAt as { toDate: () => Date }).toDate()
        : null;
      const emailedAt = data.emailedAt && typeof data.emailedAt === "object" && "toDate" in data.emailedAt && typeof (data.emailedAt as { toDate?: unknown }).toDate === "function"
        ? (data.emailedAt as { toDate: () => Date }).toDate()
        : null;
      return {
        id: document.id,
        ...data,
        createdAt: createdAt instanceof Date ? createdAt.toISOString() : null,
        emailedAt: emailedAt instanceof Date ? emailedAt.toISOString() : null,
      };
    });
    const businesses = profilesSnapshot.docs.map((document) => {
      const profile = document.data();
      const registration = registrations.get(document.id) || {};
      return {
        businessId: document.id,
        businessName: profile.businessName || registration.businessName || "Unnamed business",
        businessType: profile.businessType || registration.businessType || "general",
        ownerEmail: profile.ownerEmail || profile.email || registration.email || null,
        telemetry: telemetry.find((item) => item.businessId === document.id) || null,
        alerts: alerts.filter((alert) => alert.businessId === document.id).slice(0, 10),
      };
    });
    return NextResponse.json({ businesses, alerts, generatedAt: new Date().toISOString(), actor: actor.email }, { headers: { "cache-control": "no-store" } });
  } catch (error) {
    const details = errorResponseDetails(error);
    return responseError(details.status, details.message);
  }
}
